### 회원가입
POST http://localhost:8080/signup/customer
Content-Type: application/json

{
  "nickname": "grace",
  "password": "grace",
  "phone": "01011111111",
  "name": "grace",
  "idNumber": "990929-1111111"
}

### 로그인
POST http://localhost:8080/signin/customer
Content-Type: application/json

{
  "nickname": "grace",
  "password": "grace"
}

### 고객 상세 정보
POST http://localhost:8080/customer/getInfo?password=grace
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJOOUxLU3FSZ1FwaCtPeDdtOGoyaHVRPT0iLCJqdGkiOiIydWFIbjIyNXpOakZnb3VxTFcydklBPT0iLCJpYXQiOjE2ODc5NDExNjMsImV4cCI6MTY4Nzk0MjM2M30.q-hzfLHqjVX_1EzFfTooAvMo0WKqM9uXwRWDtYm7C70

