### 회원가입
POST http://localhost:8080/signup/customer
Content-Type: application/json

{
  "nickname": "grace",
  "password": "grace",
  "phone": "01011111111",
  "name": "grace",
  "idNumber": "990929-1111111"
}

### 로그인
POST http://localhost:8080/signin/customer
Content-Type: application/json

{
  "nickname": "grace",
  "password": "grace"
}

### 고객 상세 정보
POST http://localhost:8080/customer/getInfo?password=grace
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJOOUxLU3FSZ1FwaCtPeDdtOGoyaHVRPT0iLCJqdGkiOiJhc1psbEEzaUFiaFIrbkMvYU53L0FRPT0iLCJpYXQiOjE2ODgxMDQzOTMsImV4cCI6MTY4ODEwNTU5M30.aNILkTeAm5XHfDAfbG3oAf1PhVMnrU7vA5pEZHyqLSY

### 고객 상세 정보 변경
PUT http://localhost:8080/customer/changeInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJOOUxLU3FSZ1FwaCtPeDdtOGoyaHVRPT0iLCJqdGkiOiJhc1psbEEzaUFiaFIrbkMvYU53L0FRPT0iLCJpYXQiOjE2ODgxMDQzOTMsImV4cCI6MTY4ODEwNTU5M30.aNILkTeAm5XHfDAfbG3oAf1PhVMnrU7vA5pEZHyqLSY

{
  "password": "grace",
  "againPassword": "grace12",
  "phone": "01011111111",
  "name": "grace park"
}